
COMPILE | s2swal | intel | -DAPP=S2SWAL -DCCPP_SUITES=FV3_GFS_v17_coupled_p8,FV3_GFS_v17_coupled_p8_ugwpv1 | | fv3 |
RUN | cpld_control_p8_lnd                               | - noaacloud                           | baseline |
RUN | cpld_restart_p8_lnd                               | - noaacloud                           |          | cpld_control_p8_lnd

### CDEPS Data Atmosphere tests with LND ###
COMPILE | datm_cdeps_land | intel | -DAPP=LND | - wcoss2 | fv3 |
RUN | datm_cdeps_lnd_gswp3                              | - wcoss2                             | baseline |
RUN | datm_cdeps_lnd_era5                               | - wcoss2                             | baseline |
RUN | datm_cdeps_lnd_era5_rst                           | - wcoss2 noaacloud                   |          | datm_cdeps_lnd_era5


### ATM-LND tests ###
COMPILE | atml | intel | -DAPP=ATML -DCCPP_SUITES=FV3_GFS_v16,FV3_GFS_v16_flake,FV3_GFS_v17_p8,FV3_GFS_v17_p8_rrtmgp,FV3_GFS_v15_thompson_mynn_lam3km,FV3_WoFS_v0,FV3_GFS_v17_p8_mynn,FV3_GFS_v17_p8_ugwpv1 -D32BIT=ON | | fv3 |
RUN | control_p8_atmlnd                                 | - noaacloud wcoss2                   | baseline |
RUN | control_restart_p8_atmlnd                         | - noaacloud wcoss2                   |          | control_p8_atmlnd

COMPILE | atml_debug | intel | -DAPP=ATML -DCCPP_SUITES=FV3_GFS_v16,FV3_GFS_v16_flake,FV3_GFS_v17_p8,FV3_GFS_v17_p8_rrtmgp,FV3_GFS_v15_thompson_mynn_lam3km,FV3_WoFS_v0,FV3_GFS_v17_p8_mynn,FV3_GFS_v17_p8_ugwpv1 -D32BIT=ON -DDEBUG=ON | | fv3 |
RUN | control_p8_atmlnd_debug                           | - noaacloud wcoss2                   | baseline |

