
COMPILE | s2sw_pdlib_debug | intel | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_ugwpv1 -DPDLIB=ON -DDEBUG=ON | - noaacloud | fv3 |
RUN | cpld_debug_pdlib_p8                               | - noaacloud		               | baseline |

COMPILE | rrfs_dyn32_phy32_faster | intel | -DAPP=ATM -DFASTER=ON -DCCPP_SUITES=FV3_HRRR -D32BIT=ON -DCCPP_32BIT=ON | - noaacloud  | fv3 |
RUN | conus13km_control                                 | - noaacloud                          | baseline |
RUN | conus13km_2threads                                | - noaacloud                          |          | conus13km_control
RUN | conus13km_restart_mismatch                        | - noaacloud                          | baseline | conus13km_control

COMPILE | rrfs_dyn32_phy32_debug | intel | -DAPP=ATM -DCCPP_SUITES=FV3_RAP,FV3_HRRR,FV3_HRRR_gf -D32BIT=ON -DCCPP_32BIT=ON -DDEBUG=ON | - noaacloud  | fv3 |
RUN | conus13km_debug                                   | - noaacloud                          | baseline |
RUN | conus13km_debug_qr                                | - noaacloud                          |          |
RUN | conus13km_debug_2threads                          | - noaacloud                          |          |
RUN | conus13km_radar_tten_debug                        | - noaacloud                          | baseline |

