name: Continuous Delivery of Land DA Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Land DA CI/CD Workflow 
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: label test
        if [ ${{ github.event.label.name }} == 'bug' ]; then
          echo "bugggggggg"
        fi
        if [ ${{ github.event.label.name }} == 'test' ]; then
          echo "testtttttt"
        else
          echo "no labellllll"
        fi
      shell: bash        
